require("plugins.neo-tree")
require("plugins.themes")
require("plugins.bufferline")
require("plugins.lualine")
require("plugins.treesitter")
require("plugins.telescope")
require("plugins.lsp")
require("plugins.autocomplete")
require("plugins.autoformatting")
require("plugins.alpha")
require("core.options")
require("core.keymaps")

vim.opt.termguicolors = true
vim.cmd.colorscheme("nord")
